fix
traPtitech/knoQ pull request #163
Opened 2021-04-17 17:26 UTC by fuji8

テストの有効化とバグの修正

まだ、バグっているケースがある場合は、テストケースと共に修正する

2021-04-18 06:26 UTC, wasabi315 requested changes
https://github.com/traPtitech/knoQ/blob/60ed3a0b6210534282b5a2e9bbe3ce2b5e8b3dfe/repository/room.go#L242
ここの二個目の条件は`a.TimeEnd <= b.TimeStart`であるべきだと思う

2021-04-18 07:49 UTC, fuji8 commented
846c433 これも含む

2021-04-18 09:39 UTC, wasabi315 commented
そうなると2番目の条件は`a.TimeEnd <= b.TimeStart`であるべきでは？

2021-04-18 10:05 UTC, fuji8 commented
テスト書いて

2021-04-19 12:22 UTC, wasabi315 approved these changes

2021-04-19 12:22 UTC, merged