毎日通知のチャンネルを設定できるように、進捗部屋表示の改善
traPtitech/knoQ pull request #414
Opened 2023-06-01 07:45 UTC by Takeno-hito

- improve: 今日の進捗部屋情報を表形式にまとめた
- feat: イベントの新規・更新通知と毎日送信するチャンネルを個別に設定できるようにした

2023-06-01 08:49 UTC, ras0q requested changes
メッセージ生成処理は後で書きます
とりあえずいくつか:pray:

2023-06-01 08:49 UTC, ras0q commented on utils/cron.go
> +		if len(verifiedRoomNames) == 0 {
好みかもですが、ここから下の処理結構長くなったので`createRoomMessage`とかに分けてもいいのかなって思いました

2023-06-01 08:49 UTC, ras0q requested changes
メッセージ生成処理は後で書きます
とりあえずいくつか:pray:

2023-06-01 08:50 UTC, ras0q commented on .env.example
> +CHANNEL_ID_DAILY=
コード上でも`ActiityChannelID`になってるしそれに合わせるのがよさそう

2023-06-01 09:24 UTC, Takeno-hito commented on main.go
> +	}
後方互換性がなくなっちゃいそうでためらってたのですが大丈夫ですか？

2023-06-02 02:22 UTC, ras0q requested changes
さらにレビューしました:pray:
個人的にはsetTimeFromStringがもやってて、`time.Date`直接使えばよくない？って思ってるけどまあ読みにくくはあるのでどっちでもいいです

2023-06-05 09:39 UTC, Takeno-hito commented on utils/cron.go
> +func makeRoomArrayMapFromData(rooms []*domain.Room, timeTables []timeTable, t time.Time) []map[string]string {
なんとなくこの関数を受け取る側で 23:59:59 を指定することを要求したくない気がします（ここで 18:00 とか入れたらバグっちゃうのであんまり…？） 引数 `date` にはしてみました

2023-06-11 05:24 UTC, ras0q requested changes
みました

2023-06-11 05:24 UTC, ras0q commented on README.md
> +| CHANNEL_ID_ACTIVITY | 環境変数 | $CHANNEL_ID                            | Bot が都度送信するチャンネル                               |
変え忘れ

2023-06-11 05:24 UTC, ras0q commented on main.go
> +		handler.DailyChannelId, handler.WebhookID, handler.Origin)
これって進捗部屋以外のイベント(↓みたいなやつ)も全部DailyChannelIdに飛ぶようになると思うんですが想定していますか？
そうでなければcronを2つ走らせるのがよさそう
https://q.trap.jp/messages/51e81f13-e587-4b74-88a1-bdc49e6f353c

2023-06-11 05:24 UTC, ras0q commented on utils/cron.go
> +		if len(verifiedRoomNames) == 0 {
これって結局やらない感じですか？

2023-06-11 05:24 UTC, ras0q commented on utils/cron.go
> +
これなんか違和感あっていい書き方ないか考えてたんですが、 https://pkg.go.dev/golang.org/x/exp/slices#ContainsFunc を使うと↓みたいに書けるかもです(未検証)
```go
forceDisplay := slices.ContainsFunc(verifiedRooms, func(vr string) bool {
    return roomAvailable[i][col] != ":regional_indicator_null:"
})
if row.DisplayDefault || forceDisplay {
    // ...
}
```

2023-06-13 06:29 UTC, Takeno-hito commented on main.go
> +		handler.DailyChannelId, handler.WebhookID, handler.Origin)
イベント一覧も一緒に載ってていいと思って実装してます。微妙そうなら変えますが、特に意見無いならこのままで良いと思っています

2023-06-13 06:36 UTC, Takeno-hito commented on utils/cron.go
> +		if len(verifiedRoomNames) == 0 {
`makeRoomAvailableByTimeTable` に切り分けてそれで終わったつもりでいました まだ長そうですか？それだったら切り分けます

2023-06-13 09:09 UTC, ras0q requested changes
レビューしました:pray:

2023-06-13 09:09 UTC, ras0q commented on utils/cron_test.go
> +	stampNo := ":regional_indicator_null:"
ちょっと長くなるけど`stampAvailable`とかの方が適切かも？

2023-06-13 09:09 UTC, ras0q commented on utils/cron_test.go
> +	}{
好みなのでどっちでもいいんですが、nameをkeyにしたmapにすると構造体の中にサブテスト名が入らないかつ順番に依存しないテストが書けるのでおすすめです
めんどくさかったらそのままでいいです

2023-06-13 09:09 UTC, ras0q commented on utils/cron_test.go
> +	date := time.Now()
todayとかの方が適切かも

2023-06-13 09:09 UTC, ras0q commented on utils/cron_test.go
> +			},
IMO: この結果見てると`map[sting][]string`の方が適切では？ってなるな(なんならどうせslicesパッケージ使うなら`[][]string`でもそこまでパフォーマンスも書き心地も変わらなさそう)

2023-06-13 09:09 UTC, ras0q commented on utils/cron_test.go
> +			got := makeRoomAvailableByTimeTable(te.room, tt, time.Now())
ここは`time.Now()`じゃなくて`date`でいいはず？

2023-06-24 22:15 UTC, Takeno-hito commented on utils/cron.go
> +				toDisplay := slices.ContainsFunc(verifiedRoomNames, func(vr string) bool {
しっくり来るものが来なくて最初に提案されたforceにしました

2023-06-24 22:21 UTC, Takeno-hito commented on utils/cron_test.go
> +			},
md に書き出すときに 行→列 で配列を持った方が作りやすくてこうなってる感じですが、変えた方がいいですかね？（僕は結構どっちでもいい感じです）

2023-06-25 03:16 UTC, ras0q commented on utils/cron_test.go
> +			},
個人的には↓が見やすさでは好きなんですがこれ使ったサンプルコード書こうとしたら結構めんどくさそうだったので今のままでもいいです

時間割を最初のキーにした`map[timetableString]map[roomNameString]stampNameString`みたいなイメージのmapにすると↓とそんなに使い心地変わらないかも
```go
want: map[string]map[string]string {
  "traP-001": map[string]string {
    "1-2": stampNo,
    "3-4": stampOk,
  },
  "traP-002": map[string]string {
    "1-2": stampNo,
    "3-4": stampOk,
  },
}
```

2023-06-25 03:19 UTC, ras0q approved these changes
1点コメント返しましたが、それ以外はいいと思います！
治さなくてよさそうだったらそのままマージしちゃってOKです

2023-06-25 06:08 UTC, merged