add attendee info to ical
traPtitech/knoQ pull request #445
Opened 2023-08-02 09:53 UTC by iChemy

[arran4/golang-ical](https://github.com/arran4/golang-ical)を使用しました．

mailtoは一旦
`mailto:@ユーザー名`のような形にしています．[参考](https://github.com/traPtitech/knoQ/commit/a422a9e27b138d91d378a20ac5b6d1c6fc7a754e#diff-ca5fcd78493c2b2e0f5e6e821fd13e0ae3bcd2cb4d7060c9ad9fbb997d665942)

(確認したところ@が入ってないとappleのカレンダーではうまく参加者として表示されなかったため)

attendeeのユーザーIDからユーザー名や表示名を取るために
`func (repo *Repository) GetAtendeeMap(events []*domain.Event, info *domain.ConInfo)`
を`usecase/production`以下に作成しました．[参考](https://github.com/traPtitech/knoQ/commit/a422a9e27b138d91d378a20ac5b6d1c6fc7a754e#diff-8af98e5fc431b16513be0e0b64cd6e648b5c1b073904d7eb30a25b8d6d356954)

2023-08-02 10:02 UTC, ras0q reviewed
icalのライブラリを同時に2つ使うのは怖いので、置き換えるPRも出してもらえると助かります！🙏(別PRでも同PRでもいいです)

2023-08-02 13:05 UTC, ras0q requested changes
幾つかこめんとしました！

2023-08-18 11:07 UTC, iChemy commented
改善してみました．
お時間あるときにレビューをしていただけると嬉しいです:bow:

2023-08-27 12:46 UTC, iChemy commented
再度見てもらえると嬉しいです．何度もすみません

2023-08-27 14:07 UTC, ras0q commented on router/events.go
> +	cal.SerializeTo(&buf)
ここlinterに怒られてるので変更前みたいに
```suggestion
	_ = cal.SerializeTo(&buf)
```
してほしいです:pray: (handlingしてもいいけど)

2023-08-27 14:08 UTC, ras0q commented on router/events.go
> +	}
ココでしか使わないならGetUserMapは消してここにそのまま書く方がinterfaceへのメソッドの追加も防げていいのかなと思いました

2023-08-27 14:09 UTC, ras0q requested changes
少しだけ書きました:eyes:

2023-08-28 07:47 UTC, iChemy commented
再びご確認いただけますでしょうか.  
お手数をおかけしております 😿

2023-08-28 08:41 UTC, ras0q commented on router/events.go
>  	}
同じ`err`に対して2回エラーハンドリングしてるためこっちは消してOKです

2023-08-28 08:42 UTC, ras0q commented on presentation/event.go
> +	vevent.SetDtStampTime(time.Now())
UTCにしとくのが無難かも

2023-08-28 08:55 UTC, ras0q commented on presentation/event.go
> +	}
デフォルトは`ics.ParticipationStatusNeedsAction`でいい気がする
その上で↓のように書くと若干きれいになるかもです
`participationStatus`はgoなら`ps`とかでもいい
```go
		var participationStatus ParticipationStatus
		switch v.Schedule {
		case domain.Attendance:
			participationStatus = ics.ParticipationStatusAccepted
		case domain.Absent:
			participationStatus = ics.ParticipationStatusDeclined
		default:
			participationStatus = ics.ParticipationStatusNeedsAction
		}
		vevent.AddAttendee(userName, ics.WithCN(user.DisplayName), participationStatus)
	}
```

2023-08-28 08:58 UTC, ras0q commented on router/events.go
> +	}
上で既にハンドリングしてるのでここはいらないです

2023-08-28 09:49 UTC, iChemy commented on router/events.go
> +
上の空行に関連して疑問に思ったのですが以下の部分(`// この行に空行いれた方がいいですか?`)に空行はいれた方がいいでしょうか?
```go
	events, err := h.Repo.GetEvents(expr, info)
	if err != nil {
		return judgeErrorResponse(err)
	}
	// この行に空行いれた方がいいですか?
	users, err := h.Repo.GetAllUsers(false, true, info)
	if err != nil {
		return judgeErrorResponse(err)
	}
```

エラーハンドリング周りのコードは空行無い方が見やすいのでいれない方がいいのはわかったのですが逆に空行を入れるべきときはいつなのか気になりました．

2023-08-28 11:14 UTC, ras0q commented on router/events.go
> +
強い気持ちはないですが個人的には入れたほうがいいです
https://github.com/bombsimon/wsl とかを使うと指摘されます

2023-08-28 11:15 UTC, ras0q commented on router/events.go
> +
golangci-lintにもあります
https://golangci-lint.run/usage/linters/#wsl

2023-08-28 11:52 UTC, ras0q approved these changes
良さそうです:+1:

2023-08-28 11:55 UTC, merged