Fix/issue 400
traPtitech/knoQ pull request #461
Opened 2023-09-24 11:06 UTC by iChemy

2023-09-24 11:12 UTC, iChemy commented
そもそもフロント側が`/api/users/me/groups?relation=belongs`を叩いている気がするのでこことどのようにやりくりするべきでしょうか?([ここ](https://github.com/traPtitech/knoQ-UI/blob/5d42370fb1d48f2ac982001c484742016579aace/src/components/event/EventFormContent.vue#L145-L151C4))
`relation=belongs`で自分はbelongしてないがadminではあるチームを送るべきなのかと思い新しいクエリパラメータを暫定的に作ってコミットしました．

2023-09-24 12:10 UTC, ras0q requested changes
レビューしました

2023-09-24 12:10 UTC, ras0q commented on router/groups.go
> +		groupIDs = append(belongingGroupIDs, adminGroupIDs...)
これだと重複がある場合があると思うのでそれを弾く実装が必要な気がします

2023-09-24 12:10 UTC, ras0q commented on router/presentation/query.go
> +	case "belongsoradmins":
URLに指定するのでbelongs-or-adminsの方がいいかな
openapiにも追記してもらえると助かります:pray:

2023-09-24 12:10 UTC, ras0q commented on router/presentation/query.go
>  	return RelationBelongs
デフォルトをどうするかも考慮したい
個人的にはRelationBelongsOrAdminsが自然な気がします

2023-09-24 12:10 UTC, ras0q commented on router/groups.go
> +
最後の空行は消してもらえると助かります:pray:

2023-09-24 12:10 UTC, ras0q commented on router/groups.go
> +		}
```go
allGroupIDs := append(belongingGroupIDs, adminGroupIDs)

uniqueIDMap := make(map[uuid.UUID]struct{})
uniqueIDs := make([]uuid.UUID, 0, len(allGroupIDs))
for _, id := range allGroupIDs {
    if _, ok := uniqueIDMap[id]; ok {
        continue
    }

    uniqueIDMap[id] = struct{}{}
    uniqueIDs = append(uniqueIDs, id)
}
```
みたいに書けそうです:eyes:

2023-09-24 12:11 UTC, ras0q commented
> そもそもフロント側が`/api/users/me/groups?relation=belongs`を叩いている気がするのでこことどのようにやりくりするべきでしょうか?([ここ](https://github.com/traPtitech/knoQ-UI/blob/5d42370fb1d48f2ac982001c484742016579aace/src/components/event/EventFormContent.vue#L145-L151C4)) `relation=belongs`で自分はbelongしてないがadminではあるチームを送るべきなのかと思い新しいクエリパラメータを暫定的に作ってコミットしました．

これは新しいパラメータを作っていいと思います！
マージしたらフロント側にも置き換えるように依頼しましょう

2023-10-16 05:05 UTC, iChemy commented
遅くなりました．
確認のほどよろしくお願いします．

2023-10-16 11:38 UTC, ras0q requested changes
いくつか書きました

2023-10-16 11:38 UTC, ras0q commented on docs/swagger.yaml
> +        |値がない場合は、belongs として振る舞う
`description: |`だけで複数行かけるのでそれでいいはず

2023-10-16 11:38 UTC, ras0q commented on docs/swagger.yaml
> +        |値がない場合は、belongs として振る舞う
イベントはさらに、、の行言ってること分かりにくいけど思い出したら別PRで書き換えときます

2023-10-16 11:38 UTC, ras0q commented on router/presentation/query.go
> +	RelationBelongsOrAdmins = iota
```suggestion
	RelationBelongs         UserRelation = iota
	RelationAdmins          
	RelationBelongsOrAdmins
```
かも？今のままだとuntyped intとかになってそう

2023-11-06 09:30 UTC, iChemy commented
遅くなりました．
お時間ある際に確認のほどお願いします．

2023-11-06 14:13 UTC, ras0q approved these changes
見逃してました :bow:
よさそうです！

2023-11-11 09:24 UTC, merged