JWTtoken発行API
traPtitech/knoQ pull request #462
Opened 2023-09-24 12:33 UTC by ras0q

close https://github.com/traPtitech/knoQ/issues/422

- :sparkles: impl createToken endpoint
- :sparkles: add jwt middleware

2023-09-24 12:39 UTC, ras0q commented
UIがないのでknoQの開発環境開いてOAuth2認証をした上で
```js
await (await fetch('/api/token', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  }
})).json()
```
をしてtokenを発行します
シークレットウィンドウを開いて
```js
await (await fetch('/api/events', {
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer {ここにトークン}'
  }
})).json()
```
をするとOAuth2認証なしでイベントが取れると思います

2023-09-24 16:03 UTC, hijiki51 requested changes

2023-09-24 16:03 UTC, hijiki51 commented on router/middleware.go
> +			ContinueOnIgnoredError: true,
https://github.com/traPtitech/knoQ/pull/462/files#diff-c399d26e7f23b713ce01946ac9e0e6f1fc94d692e8a086180191901da91b6964R61

単純にここの順番を入れ替えてしまうという手段がある（隠された実装に依存するけどたぶん配列回してるだけ）

2023-10-25 10:58 UTC, ras0q commented on router/middleware.go
> +			ContinueOnIgnoredError: true,
先に部員認証しちゃうとIDが入ってなくてトークン使えなさそう

2023-10-26 11:27 UTC, ras0q commented
別の手段で最低でも30日くらいは使えるトークンにする

2024-06-10 11:21 UTC, itt828 commented
@ras0q 
> 別の手段で最低でも30日くらいは使えるトークンにする
kwsk

2024-06-21 04:59 UTC, ras0q commented
JWTで30日は長すぎるみたいな指摘が入ったからですね

2024-06-28 07:20 UTC, ras0q commented
多分これはマージされないのでクローズ

2024-06-28 07:20 UTC, closed without merging