Fix/issue439 userAPI
traPtitech/knoQ pull request #479
Opened 2023-10-26 11:30 UTC by Nzt3-gh

infra/traq/user.go のAPIを呼んでいる部分をgo traqを用いたコードに書き換えました。

2023-10-26 11:32 UTC, ras0q commented
これを実行するとコードがフォーマットされるのでまずはこれを実行してほしいです:pray:
https://github.com/traPtitech/knoQ?tab=readme-ov-file#%E3%82%B3%E3%83%BC%E3%83%89%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88

2023-10-26 13:28 UTC, ras0q requested changes
ありがとうございます！いくつかレビューしました！

2023-10-26 13:28 UTC, ras0q commented on infra/traq/user.go
> +	apiClient := traq.NewAPIClient(traqconf)
ここは多分どのAPIも共通だと思うのでメソッドにしてよさそうです

2023-10-26 13:28 UTC, ras0q commented on infra/traq/user.go
> +	userDtail, _, err := apiClient.UserApi.GetUser(context.Background(), userID.String()).Execute()
ここのcontextはAPIクライアントを作るときに使ったものと同じものを使ってほしいです！

2023-10-26 13:28 UTC, ras0q commented on utils/api.go
> +	res, err := apiClient.WebhookApi.PostWebhook(context.Background(), webhookID).XTRAQChannelId(channelID).XTRAQSignature(xTRAQSignature).Embed(int32(embed)).Body(message).Execute()
あまり行が長くなりそうなら分割すると見やすそうです

2023-10-26 13:28 UTC, ras0q commented on infra/traq/user.go
> +	userDtail, _, err := apiClient.UserApi.GetUser(context.Background(), userID.String()).Execute()
```suggestion
	userDetail, _, err := apiClient.UserApi.GetUser(context.Background(), userID.String()).Execute()
```

2023-11-10 15:43 UTC, ras0q requested changes
いくつかかきました！

2023-11-10 15:43 UTC, ras0q commented on infra/traq/traq.go
> +func MakeApiClient(token *oauth2.Token, ctx context.Context) *traq.APIClient {
contextは第1引数に取るのが慣例なのでそうして欲しいです🙏

2023-11-10 15:43 UTC, ras0q commented on infra/traq/user.go
> +	userDetail, _, err := apiClient.UserApi.GetUser(ctx, userID.String()).Execute()
レスポンスのStatus Codeもチェックするといいと思います

2023-11-10 15:43 UTC, ras0q commented on infra/traq/user.go
>  	return user, err
個人的には
```go
user := traq.User {
  Id: userDetail.Id,
  // ...
}
```
で一気に書く方が見やすいと思います

2023-11-10 15:43 UTC, ras0q commented on utils/api.go
> +	res, err := apiClient.WebhookApi.PostWebhook(context.Background(), webhookID).
動作変わらないのでどっちでもいいんですが他のところで`context.TODO`使ってくれてるので合わせると良さそう

2023-11-10 15:43 UTC, ras0q commented on utils/api.go
> +	xTRAQSignature := calcSignature(message, secret)
定義から使用までが少し離れているのでPostWebhookの行の手前とかに定義すると読みやすいと思います

2023-11-10 15:43 UTC, ras0q commented on infra/traq/traq.go
> +func MakeApiClient(token *oauth2.Token, ctx context.Context) *traq.APIClient {
ApiよりもAPIの方が好まれるので直してもらいたいです🙏
ref: https://google.github.io/styleguide/go/decisions#initialisms

あとポインタを返すならMakeよりNewっぽい気がする(割とこの関数を頻繁につかうのでNewも100%しっくり来てるわけじゃないけどGetとかRetrieveもうーんって感じなのでNewでいいです)

2023-12-20 13:27 UTC, Nzt3-gh commented
修正したので確認をお願いします。

2023-12-21 00:02 UTC, ras0q approved these changes
動作確認しました！よさそうです！

2023-12-25 11:31 UTC, merged