:bug: fix bug in SyncUsers
traPtitech/knoQ pull request #517
Opened 2024-01-19 08:58 UTC by iChemy

#504

2024-01-19 09:02 UTC, iChemy commented
`unsupported driver` エラーが ネストされた`Transaction`関数内の[これら](https://gorm.io/ja_JP/docs/transactions.html#SavePoint-RollbackTo)によって引き起こされてそうだったので[DisableNestedTransaction](https://gorm.io/ja_JP/docs/session.html#DisableNestedTransaction)を設定した．

2024-01-19 11:24 UTC, ras0q commented
saveUserがtransaction貼ってるのをやめるべきな気がする？

2024-01-19 12:47 UTC, iChemy commented
確かに．
うまく言葉にできてるかわかりませんが現在の実装を見る限り
`saveUser`でエラーが出たら外側の`SyncUsers`もエラーを吐きロールバックが起こるので

`SyncUsers`は`nil`を返すけど実は中身の`saveUser`はエラーを吐いていた!

みたいなことがないので`saveUser`はトランザクションを貼る必要はないみたいに理解しています．

2024-01-19 12:52 UTC, iChemy commented
嘘つきました

2024-01-20 01:53 UTC, ras0q commented
SyncUserで作ったtxをsaveUserの引数として渡せるのでsaveUserの1連の動作も含めて1つのtxにするのがよさそう、って意図でした(多分DisableNestedTransactionを使った時と同じ動作？)

全箇所でDisableNestedTransactionするならまだしも特定箇所だけこれするとあとで見た時になんでここだけってなるので微妙だなって思ってました

でもNested Transactionもサポートしてるはずなんだよな、、見てみます
https://gorm.io/docs/transactions.html#Nested-Transactions

2024-02-16 15:00 UTC, ras0q requested changes
文法については書きました
動作としてこれが何をしているものなのかあんまり分かってないのでもう少し詳細を書いてくれると助かります！

2024-02-17 04:17 UTC, iChemy commented
goの型キャストの仕様を調べないといけないのですが...

`dialector`型は`gorm.Dialector`インターフェース型が埋め込まれた型で`gorm.Dialector`自体には`SavePoint(tx *DB, name string) error`や`RollbackTo(tx *DB, name string) error`が一見実装されていないので，`dialector`に渡される`mysql.New()`によって返されるものが`gorm.SavePointerDialectorInterface`を実装していてもキャストできない判定になるみたいな感じかなと思っています

なので`dialector`が明示的に`gorm.SavePointerDialectorInterface`を実装していればよさそうだったのでそのように変更しました．(dockerで動かした際は正常に動くことを確認しています)

2024-02-17 04:18 UTC, iChemy commented
> goの型キャストの仕様を調べないといけないのですが...
> 
> `dialector`型は`gorm.Dialector`インターフェース型が埋め込まれた型で`gorm.Dialector`自体には`SavePoint(tx *DB, name string) error`や`RollbackTo(tx *DB, name string) error`が一見実装されていないので，`dialector`に渡される`mysql.New()`によって返されるものが`gorm.SavePointerDialectorInterface`を実装していてもキャストできない判定になるみたいな感じかなと思っています
> 
> なので`dialector`が明示的に`gorm.SavePointerDialectorInterface`を実装していればよさそうだったのでそのように変更しました．(dockerで動かした際は正常に動くことを確認しています)

2024-02-17 04:20 UTC, iChemy commented
```go
package main

type AInterface interface {
	A()
}

type BInterface interface {
	B()
}

type AStruct struct{}

func (ab AStruct) A() {
	println("ABStruct's A()!!")
}

func (ab AStruct) B() {
	println("ABStruct's B()!!")
}

type MyABStruct struct {
	AInterface
	BInterface // <-これがないと実行時エラーになる
}

func main() {
	var myABStruct MyABStruct = MyABStruct{
		AInterface: AStruct{},
	}

	myABStruct.B()
}

```
上述のコードと同じような問題だと思っています

2024-02-17 04:44 UTC, iChemy commented
めっちゃ間違えている気がしてきました
下の方が正しくこの問題を捉えられている気がします
```go
package main

type DB struct {
	d DialectorInterface
}

type DialectorInterface interface {
	dialector()
}

type SavePointerDialectorInterface interface {
	savePointerDialector()
}

type Dialector struct{}

func (d Dialector) dialector() {
	println("I am Dialector struct and implimented dialector()!!")
}

func (d Dialector) savePointerDialector() {
	println("I am Dialector struct and implimented savePointerDialector()!!")
}

func makeNewDialector() DialectorInterface {
	return Dialector{}
}

type MyDialector struct {
	DialectorInterface
}

func (db DB) RollBack() {
	if saveDialector, ok := db.d.(SavePointerDialectorInterface); ok {
		saveDialector.savePointerDialector()
	} else {
		panic("cannot caonvert db.d to SavePointerDialectorInterface!!")
	}
}

func main() {
	// var d MyDialector = MyDialector{DialectorInterface: makeNewDialector()}
	// var db DB = DB{d: d}
	// db.RollBack() // パニック
	// db.d.(SavePointerDialectorInterface).savePointerDialector() // パニック

	/*
		　下のコードはパニックにならない
	*/
	var myD DialectorInterface = makeNewDialector()
	myD.(SavePointerDialectorInterface).savePointerDialector()
}
```

2024-02-17 17:01 UTC, ras0q commented
mazreanさんがLTしてたやつだ
https://speakerdeck.com/mazrean/go-conference-mini-2023

それは置いといて、普通に僕の聞き方が抽象的過ぎたのが悪くて、`unsupported driver`の原因がネストされたtxなら(ここもこれに至った経緯とかを書いてくれると助かる)ネストを消せば解決するはずなのにそこからなんで`RollbackTo`とかに繋がるのかをあんまり理解出来ていなかったのでそこら辺を教えて欲しいです！

2024-02-19 02:41 UTC, iChemy commented
トランザクションのネストが原因だと思ったのは
`gorm`内で`unsupported driver`エラーを出し得る関数が`func (db *DB) SavePoint(name string) *DB`と`func (db *DB) RollbackTo(name string) *DB`だけでそれらが使われているのが`func (db *DB) Transaction(fc func(tx *DB) error, opts ...*sql.TxOptions) (err error)`内で`Transaction`がネストされているときにだけ呼び出されていたのでそこが原因だと思いました．
https://github.com/go-gorm/gorm/blob/8fb9a317756bc07dcaaa82d43613ddcf9295c1ad/finisher_api.go#L624C1-L636C4

2024-02-19 02:46 UTC, iChemy commented
そもそもネストを消すべきかどうかは考えてなかったので見直します

2024-02-23 11:17 UTC, iChemy commented
https://github.com/traPtitech/knoQ/pull/517#issuecomment-1900354129
> 確かに． うまく言葉にできてるかわかりませんが現在の実装を見る限り `saveUser`でエラーが出たら外側の`SyncUsers`もエラーを吐きロールバックが起こる仕様なので
> 
> `SyncUsers`は`nil`を返すけど実は中身の`saveUser`はエラーを吐いていた!
> 
> みたいなことがないので`saveUser`はトランザクションを貼る必要はないみたいに理解しています．


上のコメントから見ても`SyncUsers`内で`saveUser`を使うならトランザクションのあるなしは関係なさそうなので最初期の変更のように`DisableNestedTransaction: true`を設定しもよさそうですし`dialector`に`SavePointerDialectorInterface`を持たせてもよさそうな気はします．

今後ネストしたくなった時のためにも後者の方が良いと考えます．

2024-04-17 11:29 UTC, ras0q approved these changes
レビューが遅れてすみません！
検証はできていないのですが自作dialectorを作ったことで`gorm.SavePointerDialectorInterface`が剥がれたのが原因そうなのでこれでよさそうです！
saveUserのネストをなくすのはとりあえず他に問題が起きたときでいいかも

2024-04-20 07:24 UTC, merged

2024-06-10 11:38 UTC, iChemy commented
close #504