:sparkles: add FilterDuration and replace FilterTime in InitPostEvent…
traPtitech/knoQ pull request #544
Opened 2024-06-18 04:38 UTC by iChemy

#541

2024-06-18 04:45 UTC, iChemy commented
ある期間中(例: 今日中)にイベントが開催される瞬間があるかどうかをフィルターするために
`func FilterDuration(min, max time.Time) Expr`
を定義しこれを traQ にメッセージをポストする部分に適応させた．

`utils` パッケージ内で `func addOr(lhs, rhs Expr) Expr`というローカル関数を定義し `func FilterDuration(min, max time.Time) Expr` 内で用いている

traQに送信されるメッセージに時刻だけでなく日付の情報もわかるようにした(例)
```txt
## 06/20(Thu) の進捗部屋
本日は予約を取っていないようです。
## 06/20(Thu) 開催予定のイベント
本日開催されるイベントは、
- [イベント1](origin/events/61f5219b-ffb7-4546-9b6d-7ac1a9367c19) 06/19:13:00 ~ 06/23:13:00 @Discord 
- [イベント2](origin/events/72173508-348d-4021-8d0e-557912a09728) 06/20:12:00 ~ 06/20:18:00 @Discord
```

2024-06-18 05:51 UTC, ras0q requested changes
ありがとうございます！
幾つか書きました

2024-06-18 05:51 UTC, ras0q commented on domain/filter/shorthand.go
> +// min < max であるべき
これは直接コードで`!min.IsZero() && !max.IsZero()`であることを確認した上で時系列を判定するとよさそうです

2024-06-18 05:51 UTC, ras0q commented on domain/filter/shorthand.go
> +func FilterDuration(min, max time.Time) Expr {
最近minとmaxがbuiltinの関数名に追加されたので他の名前にしておくと余計な誤解を招かなくてよいです(動きはするんですが)

since, untilなど

2024-06-18 05:51 UTC, ras0q commented on domain/filter/shorthand.go
> +	return addOr(addOr(startIn, endIn), throughout)
addOr使わずに直接書いた方が見やすそう(この関数内のAndはそうしてるし)

2024-06-18 05:51 UTC, ras0q commented on utils/cron.go
> +				event.TimeStart.In(tz.JST).Format("01/02"), event.TimeStart.In(tz.JST).Format("15:04"), event.TimeEnd.In(tz.JST).Format("01/02"), event.TimeEnd.In(tz.JST).Format("15:04"),
`Format("01/02:15:04")`でよさそう
あと日付と時間の区切りに`:`を見るのはあまり見ないので空白区切りがいいと思います

2024-06-18 05:51 UTC, ras0q commented on domain/filter/shorthand.go
> +// time_start < min AND time_end >= max
これをORで繋ぐことを明記すると良いと思います
```suggestion
// 以下のいずれかを満たす
// - 期間中に始まる (time_start >= min AND time_start < max)
// - 期間中に終わる (time_end >= min AND time_end < max)
// - 期間より前に始まり期間より後に終わる (time_start < min AND time_end >= max)
```

2024-06-20 13:18 UTC, iChemy commented
修正してみました 🙇 
お時間ある際に確認お願いします

2024-06-20 22:28 UTC, ras0q requested changes
レビューしました！
今回のレビューはFilterDurationに関するものだけなのでまあ1コミットでもいいんですが、Refactoring codeみたいなコミットを打つと1コミットの粒度が大きくなってしまうので、1コミットでは最小単位の変更を記録してコミットを分割してくれると助かります！

2024-06-20 22:28 UTC, ras0q commented on domain/filter/shorthand.go
> +// * 期間中に始まる (time_start >= min AND time_start < max)
ここら辺のコメントもsince,untilにしてほしいです

2024-06-20 22:28 UTC, ras0q commented on domain/filter/shorthand.go
> +// since < until でない場合 nil を返す
nilを返すより返り値にエラーを追加してエラーを返すのが良さそう

2024-06-20 22:28 UTC, ras0q commented on domain/filter/shorthand.go
> +	startAfterMin := &CmpExpr{
ここもstartAfterSinceとかにしたいが流石に文法に違和感があるのであまりいい名前が思いつかない
変に変数名付けずにstartInの中に直接入れてもそこまで分かりにくくはならないとも思ったり

2024-06-21 13:47 UTC, ras0q commented on domain/filter/shorthand.go
> +// since < until でない場合 nil を返す
cron jobを作ってるからerrorが返せないのか
```go
		err := RequestWebhook(message, secret, channelID, webhookID, 1)
		if err != nil {
			fmt.Println(err)
		}
```
の部分みたいにprintしておくだけでもやっておくと良いと思います

2024-06-23 06:12 UTC, iChemy commented
新しく
```go
	if !since.IsZero() && !until.IsZero() {
		if since.After(until) {
			return nil, errors.New("invalid time range")
		}
	}
```
を返すようにしました

書いてて思ったんですが
`IsZero()`の条件のところいらない
かなと思ったのですがどう思いますか? 

こんな感じ
```go
		if since.After(until) {
			return nil, errors.New("invalid time range")
		}
```

(ただ前後関係を確認するだけの方がこの関数に想定される挙動な気がしています)

2024-06-23 20:30 UTC, ras0q commented on domain/filter/shorthand.go
> +	}
ここも上と同様throughoutの中に直接書いちゃって良さそうです

2024-06-23 20:35 UTC, ras0q commented
元のFilterTimeの実装を見るとIsZeroのときは時刻を指定しないということを意味してるようですね(knoQでは)
そうなるとそこのIsZeroはいらないんですが、別で

- since,untilがどっちも指定されている(！IsZero())ときは今の3つの条件
- sinceのみが指定されているときはsince<=終了時刻
- untilのみが指定されているときは開始時刻<=until
- どちらも指定されていない時はnil(条件なし)

を返す必要がありそうです
>
IsZero()の条件のところいらない
かなと思ったのですがどう思いますか?

2024-06-24 06:23 UTC, iChemy commented
お願いします 🙇

2024-07-01 08:01 UTC, ras0q requested changes

2024-07-01 08:01 UTC, ras0q commented on domain/filter/shorthand.go
> +		return nil, nil
ここはエラーを返したい

2024-07-01 08:03 UTC, ras0q commented on domain/filter/shorthand.go
> +		return nil, nil
嘘です
エラーはnilでいいけどExprはnilではなくて空の`&CmpExpr{}`を返すのがよさそう

2024-07-01 08:04 UTC, ras0q approved these changes
1件レビューしましたがそれ治したらマージしてOKです:thumbsup:

2024-07-01 11:16 UTC, merged